// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.ironicz.moments.entity;

import com.google.appengine.api.datastore.Email;
import com.google.appengine.api.datastore.Key;
import java.util.Date;

public class IroniczUserBuilder extends
        IroniczUserBuilderBase<IroniczUserBuilder> {
    public static IroniczUserBuilder ironiczUser() {
        return new IroniczUserBuilder();
    }

    public IroniczUserBuilder() {
        super(new IroniczUser());
    }

    public IroniczUser build() {
        return getInstance();
    }
}

class IroniczUserBuilderBase<GeneratorT extends IroniczUserBuilderBase<GeneratorT>> {
    private IroniczUser instance;

    protected IroniczUserBuilderBase(IroniczUser aInstance) {
        instance = aInstance;
    }

    protected IroniczUser getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withId(long aValue) {
        instance.setId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue) {
        instance.setName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withEmail(Email aValue) {
        instance.setEmail(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSex(String aValue) {
        instance.setSex(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAlias(String aValue) {
        instance.setAlias(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAbout(String aValue) {
        instance.setAbout(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withDob(Date aValue) {
        instance.setDob(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCountry(String aValue) {
        instance.setCountry(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPhoneNumber(String aValue) {
        instance.setPhoneNumber(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCreationDate(Date aValue) {
        instance.setCreationDate(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLastUpdatedDate(Date aValue) {
        instance.setLastUpdatedDate(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withDisabled(boolean aValue) {
        instance.setDisabled(aValue);

        return (GeneratorT) this;
    }
}
